
norm_est_RadiusSearch: 0.05
fpfh_est_RadiusSearch: 0.5

# Euclidian distance for inlier thresholding
scp_max_corr_distance: 0.05
# Maximum iterations number in RANSAC
scp_max_iter: 5000
# Similarity threshold for prerejector
scp_sim_threshold: 0.5
# Random sample first k nearest correspondences
scp_corr_randomness: 2
# Minimum inlier fraction
scp_inlier_fraction: 0.05
# Number of sample using for transformation estimation
scp_number_of_samples: 3

