
# https://rgbd-dataset.cs.washington.edu/dataset/rgbd-dataset_pcd_ascii/
# src_pcd: ../data/bun03.pcd
# target_pcd: ../data/bun4.pcd

# src_pcd: pcd/water_bottle_1_1_1.pcd
# target_pcd: pcd/water_bottle_1_1_47.pcd

# src_pcd: pcd/coffee_mug_1_1_1.pcd
# target_pcd: pcd/coffee_mug_1_1_68.pcd

# src_pcd: pcd/bun4.pcd
# target_pcd: [
#       pcd/bun01.pcd,
#       pcd/bun03.pcd,
#       ]


pcd_files_path: 
[               ref_data/trans_0.pcd,
#---------------------------------------------
                ref_data/trans_1.pcd,
                ref_data/trans_2.pcd,
                ref_data/trans_3.pcd,
                ref_data/trans_4.pcd,
                ref_data/trans_5.pcd,
]

ref_trans_path: ref_data/ref_trans.yaml

# Leaf size for grid filter
grid_filter_leafsize: 0.005
